<?php

return [
    // Default
    'APP_CLIENT_ID'=>2,
    'APP_CLIENT_SECRET'=>'jZIDNUBVkd4Do1DOmQ69ycjzqxnvkW4dfMEjnnxP',

    'PAGINATION_LIMIT'=>10,
    'VALIDATION_ERROR'=> -1000,
    'SSADMIN_ID'=>1,
    'LOGIN_SUCCESS'=>100,
    'LOGIN_UNSUCCESSFULL'=>101,
    'AUTH_DATA_GET_SUCCESS'=>102,
    'AUTH_LOGOUT'=>103,

    'UNAUTHENTICATED_RESPONSE_CODE'=>-4001,

    // module
    'MODULE_LIST_SUCCESS' =>104,
    'MODULE_INSERT_SUCCESS'=>105,
    'MODULE_INSERT_FAILED'=>-105,
    'MODULE_GET_BY_ID_SUCCESS'=>106,
    'MODULE_GET_BY_ID_FAILED'=>-106,
    'MODULE_UPDATED_FAILED'=>-107,
    'MODULE_UPDATED_SUCCESS'=>107,
    'MODULE_DELETED_FAILED'=>-108,
    'MODULE_DELETED_SUCCESS'=>108,

    // submodule
    'SUBMODULE_LIST_SUCCESS' =>109,
    'SUBMODULE_INSERT_SUCCESS'=>110,
    'SUBMODULE_INSERT_FAILED'=>-110,
    'SUBMODULE_GET_BY_ID_SUCCESS'=>111,
    'SUBMODULE_GET_BY_ID_FAILED'=>-111,
    'SUBMODULE_UPDATED_FAILED'=>-112,
    'SUBMODULE_UPDATED_SUCCESS'=>112,
    'SUBMODULE_DELETED_FAILED'=>-113,
    'SUBMODULE_DELETED_SUCCESS'=>113,

    // page
    'PAGE_LIST_SUCCESS' =>114,
    'PAGE_INSERT_SUCCESS'=>115,
    'PAGE_INSERT_FAILED'=>-116,
    'PAGE_GET_BY_ID_SUCCESS'=>117,
    'PAGE_GET_BY_ID_FAILED'=>-118,
    'PAGE_UPDATED_FAILED'=>-119,
    'PAGE_UPDATED_SUCCESS'=>120,
    'PAGE_DELETED_FAILED'=>-121,
    'PAGE_DELETED_SUCCESS'=>122,

    //user
    'USER_LIST_SUCCESS'=>123,
    'USER_DELETED_FAILED'=>124,
    'USER_DELETED_SUCCESS'=>125,
    'USER_GET_BY_ID_FAILED'=>126,
    'USER_GET_BY_ID_SUCCESS'=>127,
    'USER_PASSWORD_UPDATED_FAILED'=>128,

    //usergroup
    'USERGROUP_LIST_ASSOC_ID_SUCCESS'=>129,
    'USERGROUP_ROLE_ASSIGNED_SUCCESS'=>130,

    // Usergroup Role
    'USER_GROUP_ROLE_LIST_SUCCESS'=>131,

    // Role Page
    'ROLE_PAGE_LIST_SUCCESS'=>132,
    'ROLE_PAGE_INSERTED_FAILED'=>133,
    'ROLE_PAGE_INSERTED_SUCCESS'=>134,

    'USER_INSERT_SUCCESS'=>135,
    'ROLE_INSERT_SUCCESS'=>136

];
