export default {
    'VALIDATION_ERROR':-1000,
    'SSADMIN_ID':1,
    'LOGIN_SUCCESS':100,
    'LOGIN_UNSUCCESSFULL':101,
    'AUTH_DATA_GET_SUCCESS':102,
    'AUTH_LOGOUT':103,
    'MODULE_LIST_SUCCESS':104,
    'MODULE_INSERT_SUCCESS':105,
    'MODULE_INSERT_FAILED':-105,
    'MODULE_GET_BY_ID_SUCCESS':106,
    'MODULE_GET_BY_ID_FAILED':-106,
    'MODULE_UPDATED_FAILED':-107,
    'MODULE_UPDATED_SUCCESS':107,
    'MODULE_DELETED_FAILED':-108,
    'MODULE_DELETED_SUCCESS':108
}